import { Footer } from "@/components/footer";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navbar } from "@/components/navbar";
import { BackgroundEffects } from "@/components/ui/background-effects";
import { MouseFollower } from "@/components/ui/mouse-follower";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {" "}
        <MouseFollower />
        <BackgroundEffects />
        <Navbar />
        <div className="bg-gray-900">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
